### ISSUE TITLE
Does not load / display contents of sdcard

### ISSUE THREAD

**Issue by hackintoshlover** [acvigue/RBotFirmware#10]
Hi Aiden,
So finally after flashing sd_mmc fuses, the esp32 is detecting my sd_card but it is not loading the contents of it.

Below is verbose log of sd_card detected.

eE (573) esp_core_dump_flash: No core duy�partition found!
E (573) esp_core_dump_flash: No core dump partition found!
[     8][D][esp32-hal-cpu.c:244] setCpuFrequencyMhz(): PLL: 480 / 2 = 240 Mhz, APB: 80000000 Hz
I: Tranquil 4.5.2 (built Jul 26 2023 15:33:40)
[    47][E][Preferences.cpp:50] begin(): nvs_open failed: NOT_FOUND
[    48][D][FileManager.cpp:33] setup(): [FileManager] setup with config: {"spiffsEnabled":1,"spiffsFormatIfCorrupt":1,"sdEnabled":1,"sdLanes":1}
[   142][I][FileManager.cpp:57] setup(): [FileManager] SPIFFS registered, total size: 1013036, used: 805961
[   142][I][FileManager.cpp:70] setup(): [FileManager] setup SD mode SDMMC
[   419][I][FileManager.cpp:156] setup(): [FileManager] SD registered
[   421][I][FileManager.cpp:171] setup(): [FileManager] pattern manifest found
[   422][D][esp32FOTA.cpp:141] setString(): Assigned value: Tranquil <= Tranquil
[   428][D][esp32FOTA.cpp:141] setString(): Assigned value: https://otaserver.vigue.me/Tranquil/manifest <= https://otaserver.vigue.me/Tranquil/manifest
[   442][E][Preferences.cpp:50] begin(): nvs_open failed: NOT_FOUND
[   448][E][Preferences.cpp:50] begin(): nvs_open failed: NOT_FOUND
[   454][E][Preferences.cpp:50] begin(): nvs_open failed: NOT_FOUND
[   460][E][Preferences.cpp:50] begin(): nvs_open failed: NOT_FOUND
[   487][D][WiFiGeneric.cpp:1035] _eventCallback(): Arduino Event: 0 - WIFI_READY
[   584][V][WiFiGeneric.cpp:340] _arduino_event_cb(): STA Started
[   586][D][WiFiGeneric.cpp:1035] _eventCallback(): Arduino Event: 2 - STA_START
I: CommandScheduler: config {}
I: LedStrip: LEDs (RGBW 1) TSL enabled: 1 TSL SDA: 16 TSL SCL: 17 count 143
[   676][I][esp32-hal-i2c.c:75] i2cInit(): Initialising I2C Master: sda=16 scl=17 freq=100000
[   680][W][Wire.cpp:301] begin(): Bus already started in Master Mode.
I: LedStrip: TSL2561 detected!
I: Constructing SandBotRotary
I: MotionHelper: configMotionPipeline len 100, blockDistMM 1.00 (0=no-max), allowOoB N, jnDev 0.05
I: Axis0 params maxSpeed 15.00, acceleration 25.00, stepsPerRot 38400.00, unitsPerRot 1.00, maxRPM 4.00
I: Axis0 params minVal 0.00 (0), maxVal 0.00 (0), isDominant 0, homeOffVal 0.00, homeOffSteps 0
I: RampGenIO: Axis0 (step pin 19, dirn pin 21)
I: Axis0EndStop0 (sense 22, level 0, type 1)
I: Axis1 params maxSpeed 15.00, acceleration 25.00, stepsPerRot 3200.00, unitsPerRot 40.50, maxRPM 30.00
I: Axis1 params minVal 0.00 (0), maxVal 145.00 (1), isDominant 0, homeOffVal 0.00, homeOffSteps 0
I: RampGenIO: Axis1 (step pin 27, dirn pin 3)
I: Axis1EndStop0 (sense 23, level 0, type 1)
I: MotionHoming: config sequence FR3;A+38400n;B+3200;#;A+38400N;B+3200;#;A+200;#B+400;#;B+30000n;#;B-30000N;#;B-340;#;A=h;B=h;$
V: TrinamicsController: configure {"model":"SandBotRotary","motionController":{"chip":"TMC2209","TX1":32,"TX2":33,"driver_TOFF":4,"run_current":600,"microsteps":16,"stealthChop":1},"homing":{"homingSeq":"FR3;A+38400n;B+3200;#;A+38400N;B+3200;#;A+200;#B+400;#;B+30000n;#;B-30000N;#;B-340;#;A=h;B=h;$","maxHomingSecs":120},"blockDistanceMM":1,"allowOutOfBounds":0,"stepEnablePin":"25","stepEnLev":0,"stepDisableSecs":30,"axis0":{"maxSpeed":15,"maxAcc":25,"maxRPM":4,"stepsPerRot":38400,"stepPin":"19","dirnPin":"21","dirnRev":"1","endStop0":{"sensePin":"22","actLvl":0,"inputType":"INPUT"}},"axis1":{"maxSpeed":15,"maxAcc":25,"maxRPM":30,"stepsPerRot":3200,"unitsPerRot":40.5,"maxVal":145,"stepPin":"27","dirnRev":"1","dirnPin":"3","endStop0":{"sensePin":"23","actLvl":0,"inputType":"INPUT"}}}
I: MotorEnabler: (pin 25, actLvl 0, disableAfter 30.00s)
I: RampGenerator: Starting ISR timer for direct stepping
[   963][W][esp32-hal-timer.c:226] timerAttachInterruptFlag(): EDGE timer interrupt is not supported! Setting to LEVEL...
I: WorkManager: cmdsAtStart <>
I: WorkManager: startup commands <>
V: WorkManager: status changed 0 0
I: WiFiManager: notConn WiFi.begin SSID Home attempt 0
[  2025][V][WiFiGeneric.cpp:97] set_esp_interface_ip(): Configuring Station static IP: 0.0.0.0, MASK: 0.0.0.0, GW: 0.0.0.0
[  2852][V][WiFiGeneric.cpp:355] _arduino_event_cb(): STA Connected: SSID: Home, BSSID: 9c:a2:f4:c8:fe:dc, Channel: 6, Auth: WPA2_PSK
[  2854][D][WiFiGeneric.cpp:1035] _eventCallback(): Arduino Event: 4 - STA_CONNECTED
[  3548][V][WiFiGeneric.cpp:369] _arduino_event_cb(): STA Got New IP:192.168.0.110
[  3549][D][WiFiGeneric.cpp:1035] _eventCallback(): Arduino Event: 7 - STA_GOT_IP
[  3553][D][WiFiGeneric.cpp:1098] _eventCallback(): STA IP: 192.168.0.110, MASK: 255.255.255.0, GW: 192.168.0.1
I: WiFiManager: GotIP 192.168.0.110
I: WebServer: begun
I: WiFiManager: mDNS responder started with hostname Tranquil
V: WorkManager: status changed 0 0
I: NTPClient: service - configTime set
V: WorkManager: status changed 0 0
V: CommandScheduler: service failed to get time
V: WorkManager: status changed 0 0
V: CommandScheduler: service failed to get time
V: WorkManager: status changed 0 0
V: WebServer: Calling settings/led url /settings/led
V: RestAPIRobot: GetLEDConfig { "rslt": "unknown" }
[ 36143][W][AsyncTCP.cpp:930] _poll(): pcb is NULL
I: RestAPIRobot: SetLedBody len 228, {"ledOn":1,"ledBrightness":127,"primaryRedVal":127,"primaryGreenVal":127,"primaryBlueVal":127,"secRedVal":127,"secGreenVal":127,"secBlueVal":127,"effectID":0,"effectSpeed":50,"autoDim":0,"autoDimStrength":15,"ledAngleOffset":15}
V: WebServer: Calling settings/led url /settings/led
I: RestAPIRobot: SetLed /settings/led
V: WorkManager: status changed 0 0
[ 42522][W][AsyncTCP.cpp:950] _poll(): rx timeout 4
V: WebServer: Calling settings/tranquil url /settings/tranquil
[ 49030][W][AsyncTCP.cpp:950] _poll(): rx timeout 4
V: WorkManager: status changed 0 0
[ 51030][W][AsyncTCP.cpp:943] _poll(): ack timeout 4
[ 55539][W][AsyncTCP.cpp:943] _poll(): ack timeout 4
V: WorkManager: status changed 0 0

Below is the image of contents in my sd_card:
![Screenshot (155)](https://github.com/acvigue/TranquilFirmware/assets/40655406/c70ebdfc-2f02-45cb-9aa2-2ac72c155cce)

Below is the image of webpage being diplayed after everything is working fine but without displaying patterns:
![Screenshot (158)](https://github.com/acvigue/TranquilFirmware/assets/40655406/a550baef-4e92-42fd-b3dd-a21af6a8b07e)

Also it is asking for sign-in to continue.

What to do?

**Comment by acvigue** [comment]
I'm currently working on registration for the API service. Your SD card needs to be EMPTY - the robot manages all files on there.

**Comment by hackintoshlover** [comment]
> I'm currently working on registration for the API service. Your SD card needs to be EMPTY - the robot manages all files on there.

Ok.
Waiting for it to happen.
Just a quick question, what to do if i want to load files cureently on my sdcard?
Is there a way to use the table without the registration api for now so that i can start tesing it with the sand table?

**Comment by acvigue** [comment]
No.
