### ISSUE TITLE
Wrong GT2 belt size listed on instructables

### ISSUE THREAD

**Issue by aepkolol** [acvigue/RBotFirmware#11]
Hey! Great project, I'm still working on getting it running right now.

On the instructibles webpage, it says to use a 400mm GT2 belt, so I ordered some. They are the wrong size, they won't even fit around the gear, let alone reaching the drive shaft. 

I also ordered 3 inch bearings, not 4 inch.. So that one is on me. 

I modified the Theta gear in the fusion360 file to work with both a 3" bearing and a 400mm GT2 belt. Currently I'm trying to get the SD card to work (I just soldered the SD card to the ESP32, arduino IDE "SD Test" can see it, but this program can't. Waiting on an adaptor from Amazon) so I haven't tested if my modification works or not.

<img width="635" alt="Screenshot 2023-08-17 163906" src="https://github.com/acvigue/TranquilFirmware/assets/28993017/ead3f24d-6f4f-4e00-95c9-5f5df1215a3c">

My question is... Is there anything I have to change since the gear radius has changed?  I'm not much of a math guy, but I assume the ratios are off now.

**Comment by gk1089** [comment]
@aepkolol I am sorry for barging in on your discussion. I want to build a sandbox for myself and this being the cheapest option, has my attention. Problem is, this is a first of its kind project for me. I have experience with simple stuff like sensors based projects on arduino. But mechatronics projects like these feel very daunting to me right now. On his Instructables page, @acvigue has admitted that the project is not documented to be useful for a novice like me.

Since you are already undergoing this journey, will you be willing to let me tag along? If you agree, please share your email address or drop me a line at gaurav1089 -AT- gmail -DOT- com. 

Cheers!

**Comment by acvigue** [comment]
Yes, I am sorry about the documentation. It's understandably a very daunting project and while I tried to include everything that I could remember, there are many parts that I left out. The 400mm belt is the one I used on my robot though, so I don't see why that isn't working. You change the gear ratio in the robot configuration. It's represented as "number of microsteps that cause 1 full rotation of the central gears"

**Comment by aepkolol** [comment]
> @aepkolol I am sorry for barging in on your discussion. I want to build a sandbox for myself and this being the cheapest option, has my attention. Problem is, this is a first of its kind project for me. I have experience with simple stuff like sensors based projects on arduino. But mechatronics projects like these feel very daunting to me right now. On his Instructables page, @acvigue has admitted that the project is not documented to be useful for a novice like me.
> 
> Since you are already undergoing this journey, will you be willing to let me tag along? If you agree, please share your email address or drop me a line at gaurav1089 -AT- gmail -DOT- com.
> 
> Cheers!

I am making a guide for people here: https://github.com/aepkolol/TranquilFirmware/blob/main/README.md

I am not done it yet, I have to head out now. I'll keep adding to it, but hopefully it helps a bit there. 



> Yes, I am sorry about the documentation. It's understandably a very daunting project and while I tried to include everything that I could remember, there are many parts that I left out. The 400mm belt is the one I used on my robot though, so I don't see why that isn't working. You change the gear ratio in the robot configuration. It's represented as "number of microsteps that cause 1 full rotation of the central gears"

Honestly not sure whats up with the belt thing. I just counted the teeth and did the math and changed what you said and it works great. Also changed up a few other things. 

I see I have to login to some API thing for me to upload gcode and actually use this however. The link on the readme is broken though, so I can't that up.. :( 

What is the purpose of the API? it seems like this firmware is more than capable of running on my local network alone.

**Comment by acvigue** [comment]
The API provides a hosted pattern library where patterns can be downloaded from. It's intended to be run on Cloudflare Workers and the endpoint can be changed in the Vue app.

**Comment by gk1089** [comment]
@aepkolol Thank you for your tutorial. It gives a great perspective on the project and clarifies many of the intermediate points. I have some queries that I shall post here. Please answer them if you can. It may help others in the same boat as me:
1. The pancake NEMA 17s are difficult to come by where I am. I already have the normal size NEMA 17 stepper motors having 6 leads. Will that have any effect on the plans apart from making the final table thicker?
![image](https://github.com/acvigue/TranquilFirmware/assets/20543555/d1f18a20-3ced-4127-930e-d26b1a6a5057)
3. My generic TMC2208 (v2.0) looks similar to the one posted on your tutorial, apart from calling UART as USART. I have done some basic motor movement project in legacy mode but not in UART mode. Did you have to solder any of the pins/pads together to get it working. If you are aware of any simple projects based on UART mode, please share them.
4. To begin with, I do not intend to pull the pattern files from the internet/LAN based repository. Is there a particular folder in which the files should reside in the SD card for it to be used? Does the firmware allow the users to choose, add to a 'playlist'? Screenshots of the UI would be very helpful in getting this answered. @acvigue 

Cheers!

**Comment by acvigue** [comment]
> Does the firmware allow the users to choose, add to a 'playlist'? Screenshots of the UI would be very helpful in getting this answered.

The firmware relies on a root `manifest.json` file containing two arrays, `playlists` and `patterns`. The types of these arrays are defined in the Vue code. The patterns are named as `uuid.thr` and playlists are a newline-seperated plain text file, each line containing the file name of a pattern. They are named as `playlist-uuid.seq`. The Web UI should work if you manually place files on it, however the pattern previews won't load. I'm working on making the API multi-user compatible.

**Comment by aepkolol** [comment]
@gk1089 @acvigue choose the pancake steppers because they are thin enough to fit between the mounting plate and the enclosure. If you want to use a thicker motor, you would need to extend the depth of the enclosure to fit them. They would also be much more powerful than you'd need, but that's not really an issue. 

USART and UART can be used interchangeably in this case. I haven't read through the code, since it uses a library for the stepper motor. I'm not sure if it even needs the TX connected, but it doesn't hurt. 

I haven't worked on this for a few days, been too busy. I was unable to get the API server running, or figure out how to run anything off the SD card. If I figure it out, I'll let you know. @acvigue's last comment gives me a clue.

**Comment by acvigue** [comment]
> USART and UART can be used interchangeably in this case. I haven't read through the code, since it uses a library for the stepper motor. I'm not sure if it even needs the TX connected, but it doesn't hurt.

Trinamic UART mode can be disabled in the robot config, this way you can just use CFG pins / jumpers.
