### ISSUE TITLE
TranquilAPI needed?

### ISSUE THREAD

**Issue by cumbaya** [acvigue/RBotFirmware#14]
Hi.
I built a Sand-Robot and found your firmware/GUI here on GitHub.
Two questions:
Is it usable for a "one-arm-scara-bot"?
Is it usable without the TranquilAPI-server? So, I want to use it only with files/patterns on the sd-card.
Thanks for your work.
Timo

**Comment by acvigue** [comment]
Currently no, and no.

**Comment by cumbaya** [comment]
I saw, you built an one-arm-bot. So, which firmware did you use for it?

**Comment by acvigue** [comment]
I used Rob Dobson's firmware with a custom frontend that I no longer have the code for...

However, you may be able to recompile SCARA support in if you add the corresponding RobotGeometry files
