### ISSUE TITLE
Compile Error

### ISSUE THREAD

**Issue by hackintoshlover** [acvigue/RBotFirmware#6]
When compiling version 4.5.0, compiler gives below errors:

src/WorkManager/WorkManager.h:33:23: error: 'WorkManager::_wireGuardManager' will be initialized after [-Werror=reorder]
     WireGuardManager& _wireGuardManager;
                       ^
src/WorkManager/WorkManager.h:31:20: error:   'RestAPISystem& WorkManager::_restAPISystem' [-Werror=reorder]
     RestAPISystem& _restAPISystem;
                    ^
src/WorkManager/WorkManager.cpp:14:1: error:   when initialized here [-Werror=reorder]
 WorkManager::WorkManager(ConfigBase &mainConfig, ConfigBase &robotConfig, RobotController &robotController, LedStrip &ledStrip, WireGuardManager &wireGuardManager,
 ^
Compiling .pio\build\dev\lib071\WiFi\WiFiUdp.cpp.o
Compiling .pio\build\dev\lib5a8\ESP Async WebServer\AsyncEventSource.cpp.o
Archiving .pio\build\dev\libf75\libAsyncTCP.a
Compiling .pio\build\dev\lib5a8\ESP Async WebServer\AsyncWebSocket.cpp.o
Compiling .pio\build\dev\lib5a8\ESP Async WebServer\SPIFFSEditor.cpp.o
Compiling .pio\build\dev\lib5a8\ESP Async WebServer\WebAuthentication.cpp.o
cc1plus.exe: some warnings being treated as errors
*** [.pio\build\dev\src\WorkManager\WorkManager.cpp.o] Error 1
=========================================================== [FAILED] Took 11.36 seconds ===========================================================

 *  The terminal process "C:\Users\mishr\.platformio\penv\Scripts\platformio.exe 'run'" terminated with exit code: 1. 
 *  Terminal will be reused by tasks, press any key to close it.

**Comment by acvigue** [comment]
Please use code tags and only post the relevant information.
Both GitHub Actions and my computer are able to successfully compile the project, and have been able to for a while now.

<img width="1103" alt="Screenshot 2023-07-24 at 8 45 26 PM" src="https://github.com/acvigue/TranquilFirmware/assets/34462061/e6eb8dfe-fbbf-42a2-8746-b0b1d11c9186">

**Comment by acvigue** [comment]
<img width="1071" alt="Screenshot 2023-07-24 at 8 46 43 PM" src="https://github.com/acvigue/TranquilFirmware/assets/34462061/c9a83818-7473-4c16-92b6-bf8f55862a03">

**Comment by hackintoshlover** [comment]
Using firmware version 4.5.2 https://github.com/acvigue/TranquilFirmware/commit/e905f35e049b0cb6d686164c88f1c1146340d934

still getting compiler error
![Screenshot (142)](https://github.com/acvigue/TranquilFirmware/assets/40655406/4d018477-2ebc-425f-ad83-e85a11c77701)

Can you tell what version of platformio and esp32core you are using to compile?
I suspect this an issue since while compilin rob,s firmware, it compiles only if platformio v2.2.1 and esp32core v2.1.0 is used else it gives compiler error.

**Comment by hackintoshlover** [comment]
> Using firmware version 4.5.2 [e905f35](https://github.com/acvigue/TranquilFirmware/commit/e905f35e049b0cb6d686164c88f1c1146340d934)
> 
> still getting compiler error ![Screenshot (142)](https://user-images.githubusercontent.com/40655406/255832324-4d018477-2ebc-425f-ad83-e85a11c77701.png)
> 
> Can you tell what version of platformio and esp32core you are using to compile? I suspect this an issue since while compilin rob,s firmware, it compiles only if platformio v2.2.1 and esp32core v2.1.0 is used else it gives compiler error.

Could you provide firmware.bin that works on your setup?

**Comment by ScottFal** [comment]
I've been able to compile for a while also, these are the platform version I have installed, I've had trouble when different versions are installed. version 4.5.2 also works for me when uploaded, 8.8.4.4 will show the webpage, 
im unsure how to navigate to the application after I've connected it to my internet and its got an ip
![image](https://github.com/acvigue/TranquilFirmware/assets/72571206/078bd073-c21a-4755-9d51-1319527920aa)

**Comment by hackintoshlover** [comment]
> > Using firmware version 4.5.2 [e905f35](https://github.com/acvigue/TranquilFirmware/commit/e905f35e049b0cb6d686164c88f1c1146340d934)
> > still getting compiler error ![Screenshot (142)](https://user-images.githubusercontent.com/40655406/255832324-4d018477-2ebc-425f-ad83-e85a11c77701.png)
> > Can you tell what version of platformio and esp32core you are using to compile? I suspect this an issue since while compilin rob,s firmware, it compiles only if platformio v2.2.1 and esp32core v2.1.0 is used else it gives compiler error.
> 
> Could you provide firmware.bin that works on your setup?

Updated to Platformio V3.4.4 and esp32 core 6.3.2
Now it compiles and upload without error but webpage does not load.
![Screenshot (146)](https://github.com/acvigue/TranquilFirmware/assets/40655406/7e5aa5ed-de91-4fbc-9682-80d324c96cb6)

**Comment by hackintoshlover** [comment]
> I've been able to compile for a while also, these are the platform version I have installed, I've had trouble when different versions are installed. version 4.5.2 also works for me when uploaded, 8.8.4.4 will show the webpage, im unsure how to navigate to the application after I've connected it to my internet and its got an ip ![image](https://user-images.githubusercontent.com/72571206/255844971-078bd073-c21a-4755-9d51-1319527920aa.png)

For me webpage does not load.
Just shows Tranquil icon on chrome tab.

**Comment by acvigue** [comment]
> I've been able to compile for a while also, these are the platform version I have installed, I've had trouble when different versions are installed. version 4.5.2 also works for me when uploaded, 8.8.4.4 will show the webpage,
> im unsure how to navigate to the application after I've connected it to my internet and its got an ip
> ![image](https://user-images.githubusercontent.com/72571206/255844971-078bd073-c21a-4755-9d51-1319527920aa.png)

what issues are you having w the webapp

**Comment by ScottFal** [comment]
> > I've been able to compile for a while also, these are the platform version I have installed, I've had trouble when different versions are installed. version 4.5.2 also works for me when uploaded, 8.8.4.4 will show the webpage,
> > im unsure how to navigate to the application after I've connected it to my internet and its got an ip
> > ![image](https://user-images.githubusercontent.com/72571206/255844971-078bd073-c21a-4755-9d51-1319527920aa.png)
> 
> what issues are you having w the webapp


It seems to be uploading fine to the esp, can connect to 8.8.4.4 and it has all of the UI, I type in my wifi credentials, and it connects, but I don't know where to go from here. when I go to the IP I get "This site can’t be reached"

``` *  Executing task: C:\Users\Scott\.platformio\penv\Scripts\platformio.exe device monitor 


Please build project in debug configuration to get more details about an exception.
See https://docs.platformio.org/page/projectconf/build_configurations.html


--- Terminal on COM3 | 115200 8-N-1
--- Available filters and text transformations: colorize, debug, default, direct, esp32_exception_decoder, hexlify, log2file, nocontrol, printable, send_on_enter, time
--- More details at https://bit.ly/pio-monitor-filters
--- Quit: Ctrl+C | Menu: Ctrl+T | Help: Ctrl+T followed by Ctrl+H
ets Jul 29 2019 12:21:46

rst:0x1 (POWERON_RESET),boot:0x13 (SPI_FAST_FLASH_BOOT)
configsip: 0, SPIWP:0xee
clk_drv:0x00,q_drv:0x00,d_drv:0x00,cs0_drv:0x00,hd_drv:0x00,wp_drv:0x00
mode:DIO, clock div:1
load:0x3fff0030,len:1184
load:0x40078000,len:13220
ho 0 tail 12 room 4
load:0x40080400,len:3028
entry 0x400805e4
E (481) esp_core_dump_flash:�
                             �ɕ�dump partition found!
E (481) esp_core_dump_flash: No core dump partition found!
I: Tranquil 4.5.2 (built Jul 25 2023 14:48:49)
[    38][E][Preferences.cpp:50] begin(): nvs_open failed: NOT_FOUND
E (348) sdmmc_common: sdmmc_init_ocr: send_op_cond (1) returned 0x107
E (349) vfs_fat_sdmmc: sdmmc_card_init failed (0x107).
[   353][E][FileManager.cpp:150] setup(): [FileManager] !!!!!!!!!!!!!!!!!!!!!!!!!!!
[   360][E][FileManager.cpp:151] setup(): [FileManager] failed to init SD, error ESP_ERR_TIMEOUT
[   369][E][FileManager.cpp:152] setup(): [FileManager] !!!!!!!!!!!!!!!!!!!!!!!!!!!
[   376][E][FileManager.cpp:177] setup(): [FileManager] filesystems must both be marked online to ensure functionality...
[   387][E][FileManager.cpp:178] setup(): [FileManager] SD: offline
[   393][E][FileManager.cpp:179] setup(): [FileManager] SPIFFS: online
[   400][E][Preferences.cpp:50] begin(): nvs_open failed: NOT_FOUND
[   405][E][Preferences.cpp:50] begin(): nvs_open failed: NOT_FOUND
[   411][E][Preferences.cpp:50] begin(): nvs_open failed: NOT_FOUND
[   417][E][Preferences.cpp:50] begin(): nvs_open failed: NOT_FOUND
I: CommandScheduler: config {}
I: LedStrip: LEDs (RGBW 1) TSL enabled: 1 TSL SDA: 16 TSL SCL: 17 count 143
I: LedStrip: TSL2561 detected!
I: Constructing SandBotRotary
I: MotionHelper: configMotionPipeline len 100, blockDistMM 1.00 (0=no-max), allowOoB N, jnDev 0.05
I: Axis0 params maxSpeed 15.00, acceleration 25.00, stepsPerRot 38400.00, unitsPerRot 1.00, maxRPM 4.00
I: Axis0 params minVal 0.00 (0), maxVal 0.00 (0), isDominant 0, homeOffVal 0.00, homeOffSteps 0
I: RampGenIO: Axis0 (step pin 19, dirn pin 21)
I: Axis0EndStop0 (sense 22, level 0, type 1)
I: Axis1 params maxSpeed 15.00, acceleration 25.00, stepsPerRot 3200.00, unitsPerRot 40.50, maxRPM 30.00
I: Axis1 params minVal 0.00 (0), maxVal 145.00 (1), isDominant 0, homeOffVal 0.00, homeOffSteps 0
I: RampGenIO: Axis1 (step pin 27, dirn pin 3)
I: Axis1EndStop0 (sense 23, level 0, type 1)
I: MotionHoming: config sequence FR3;A+38400n;B+3200;#;A+38400N;B+3200;#;A+200;#B+400;#;B+30000n;#;B-30000N;#;B-340;#;A=h;B=h;$
I: MotorEnabler: (pin 25, actLvl 0, disableAfter 30.00s)
I: RampGenerator: Starting ISR timer for direct stepping
I: WorkManager: cmdsAtStart <>
I: WorkManager: startup commands <>
I: WiFiManager: notConn WiFi.begin SSID SKYRQW5K attempt 0
I: WiFiManager: GotIP 192.168.0.51
I: WebServer: begunI: WiFiManager: mDNS responder started with hostname Tranquil

I: NTPClient: service - configTime set```
