### ISSUE TITLE
Webpage does not load

### ISSUE THREAD

**Issue by hackintoshlover** [acvigue/RBotFirmware#7]
Using Platformio V3.4.4 and esp32 core 6.3.2 the code compiles but webpage does not load.
![Screenshot (146)](https://github.com/acvigue/TranquilFirmware/assets/40655406/d7de905b-9fab-4b81-8e21-0ae0229d1114)

Below is the verbose output:

rst:0xc (SW_CPU_RESET),boot:0x13 (SPI_FAST_FLASH_BOOT)
configsip: 0, SPIWP:0xee
clk_drv:0x00,q_drv:0x00,d_drv:0x00,cs0_drv:0x00,hd_drv:0x00,wp_drv:0x00
mode:DIO, clock div:2
load:0x3fff0030,len:1184
load:0x40078000,len:13192
load:0x40080400,len:3028
entry 0x400805e4
E (573) esp_core_dump_flash: No core du��partition found!
E (573) esp_core_dump_flash: No core dump partition found!
[     8][D][esp32-hal-cpu.c:244] setCpuFrequencyMhz(): PLL: 480 / 2 = 240 Mhz, APB: 80000000 Hz
I: Tranquil 4.5.2 (built Jul 25 2023 15:38:13)
[    43][E][Preferences.cpp:50] begin(): nvs_open failed: NOT_FOUND
[    44][E][Preferences.cpp:50] begin(): nvs_open failed: NOT_FOUND
[    46][D][FileManager.cpp:33] setup(): [FileManager] setup with config: {"spiffsEnabled":1,"spiffsFormatIfCorrupt":1,"sdEnabled":1,"sdLanes":1}
[   144][I][FileManager.cpp:57] setup(): [FileManager] SPIFFS registered, total size: 1013036, used: 805961
[   145][I][FileManager.cpp:70] setup(): [FileManager] setup SD mode SDMMC
E (373) sdmmc_common: sdmmc_init_ocr: send_op_cond (1) returned 0x107
E (374) vfs_fat_sdmmc: sdmmc_card_init failed (0x107).
[   380][E][FileManager.cpp:150] setup(): [FileManager] !!!!!!!!!!!!!!!!!!!!!!!!!!!
[   387][E][FileManager.cpp:151] setup(): [FileManager] failed to init SD, error ESP_ERR_TIMEOUT
[   396][E][FileManager.cpp:152] setup(): [FileManager] !!!!!!!!!!!!!!!!!!!!!!!!!!!
[   403][E][FileManager.cpp:177] setup(): [FileManager] filesystems must both be marked online to ensure functionality...
[   414][E][FileManager.cpp:178] setup(): [FileManager] SD: offline
[   420][E][FileManager.cpp:179] setup(): [FileManager] SPIFFS: online
[   427][D][esp32FOTA.cpp:141] setString(): Assigned value: Tranquil <= Tranquil
[   433][D][esp32FOTA.cpp:141] setString(): Assigned value: https://otaserver.vigue.me/Tranquil/manifest <= https://otaserver.vigue.me/Tranquil/manifest
[   447][E][Preferences.cpp:50] begin(): nvs_open failed: NOT_FOUND
[   453][E][Preferences.cpp:50] begin(): nvs_open failed: NOT_FOUND
[   459][E][Preferences.cpp:50] begin(): nvs_open failed: NOT_FOUND
[   465][E][Preferences.cpp:50] begin(): nvs_open failed: NOT_FOUND
[   491][D][WiFiGeneric.cpp:1035] _eventCallback(): Arduino Event: 0 - WIFI_READY
[   591][V][WiFiGeneric.cpp:340] _arduino_event_cb(): STA Started
[   592][D][WiFiGeneric.cpp:1035] _eventCallback(): Arduino Event: 2 - STA_START
I: CommandScheduler: config {}
I: LedStrip: LEDs (RGBW 1) TSL enabled: 1 TSL SDA: 16 TSL SCL: 17 count 143
[   626][I][esp32-hal-i2c.c:75] i2cInit(): Initialising I2C Master: sda=16 scl=17 freq=100000
[   629][W][Wire.cpp:301] begin(): Bus already started in Master Mode.
I: LedStrip: TSL2561 detected!
I: Constructing SandBotRotary
I: MotionHelper: configMotionPipeline len 100, blockDistMM 1.00 (0=no-max), allowOoB N, jnDev 0.05
I: Axis0 params maxSpeed 15.00, acceleration 25.00, stepsPerRot 38400.00, unitsPerRot 1.00, maxRPM 4.00
I: Axis0 params minVal 0.00 (0), maxVal 0.00 (0), isDominant 0, homeOffVal 0.00, homeOffSteps 0
I: RampGenIO: Axis0 (step pin 19, dirn pin 21)
I: Axis0EndStop0 (sense 22, level 0, type 1)
I: Axis1 params maxSpeed 15.00, acceleration 25.00, stepsPerRot 3200.00, unitsPerRot 40.50, maxRPM 30.00
I: Axis1 params minVal 0.00 (0), maxVal 145.00 (1), isDominant 0, homeOffVal 0.00, homeOffSteps 0
I: RampGenIO: Axis1 (step pin 27, dirn pin 3)
I: Axis1EndStop0 (sense 23, level 0, type 1)
I: MotionHoming: config sequence FR3;A+38400n;B+3200;#;A+38400N;B+3200;#;A+200;#B+400;#;B+30000n;#;B-30000N;#;B-340;#;A=h;B=h;$
V: TrinamicsController: configure {"model":"SandBotRotary","motionController":{"chip":"TMC2209","TX1":32,"TX2":33,"driver_TOFF":4,"run_current":600,"microsteps":16,"stealthChop":1},"homing":{"homingSeq":"FR3;A+38400n;B+3200;#;A+38400N;B+3200;#;A+200;#B+400;#;B+30000n;#;B-30000N;#;B-340;#;A=h;B=h;$","maxHomingSecs":120},"blockDistanceMM":1,"allowOutOfBounds":0,"stepEnablePin":"25","stepEnLev":0,"stepDisableSecs":30,"axis0":{"maxSpeed":15,"maxAcc":25,"maxRPM":4,"stepsPerRot":38400,"stepPin":"19","dirnPin":"21","dirnRev":"1","endStop0":{"sensePin":"22","actLvl":0,"inputType":"INPUT"}},"axis1":{"maxSpeed":15,"maxAcc":25,"maxRPM":30,"stepsPerRot":3200,"unitsPerRot":40.5,"maxVal":145,"stepPin":"27","dirnRev":"1","dirnPin":"3","endStop0":{"sensePin":"23","actLvl":0,"inputType":"INPUT"}}}
I: MotorEnabler: (pin 25, actLvl 0, disableAfter 30.00s)
I: RampGenerator: Starting ISR timer for direct stepping
[   912][W][esp32-hal-timer.c:226] timerAttachInterruptFlag(): EDGE timer interrupt is not supported! Setting to LEVEL...
I: WorkManager: cmdsAtStart <>
I: WorkManager: startup commands <>
V: WorkManager: status changed 0 0
I: WiFiManager: notConn WiFi.begin SSID  attempt 0
I: WiFiManager: starting softap (Tranquil)
[  2025][V][WiFiGeneric.cpp:343] _arduino_event_cb(): STA Stopped
[  2028][V][WiFiGeneric.cpp:392] _arduino_event_cb(): AP Started
[  2028][D][WiFiGeneric.cpp:1035] _eventCallback(): Arduino Event: 3 - STA_STOP
[  2072][D][WiFiGeneric.cpp:1035] _eventCallback(): Arduino Event: 10 - AP_START
[  2081][V][WiFiGeneric.cpp:97] set_esp_interface_ip(): Configuring SoftAP static IP: 8.8.4.4, MASK: 255.255.255.0, GW: 8.8.4.4
[  2084][V][WiFiGeneric.cpp:395] _arduino_event_cb(): AP Stopped
[  2091][D][WiFiGeneric.cpp:1035] _eventCallback(): Arduino Event: 11 - AP_STOP
[  2098][V][WiFiGeneric.cpp:392] _arduino_event_cb(): AP Started
[  2104][D][WiFiGeneric.cpp:1035] _eventCallback(): Arduino Event: 10 - AP_START
[  2111][V][WiFiGeneric.cpp:143] set_esp_interface_ip(): SoftAP: 8.8.4.4 | Gateway: 8.8.4.4 | DHCP Start: 0.0.0.0 | Netmask: 255.255.255.0
[  2123][V][WiFiGeneric.cpp:190] set_esp_interface_ip(): DHCP Server Range: 8.8.4.5 to 8.8.4.15
I: WiFiManager:  softap ip: 8.8.4.4
I: WebServer: begun
[  6763][V][WiFiGeneric.cpp:407] _arduino_event_cb(): AP Station Connected: MAC: 3c:21:9c:82:e8:3f, AID: 1
[  6764][D][WiFiGeneric.cpp:1035] _eventCallback(): Arduino Event: 12 - AP_STACONNECTED
[  6776][E][WiFiUdp.cpp:185] endPacket(): could not send data: 12
[  6918][V][WiFiGeneric.cpp:421] _arduino_event_cb(): AP Station IP Assigned:8.8.4.5
[  6920][D][WiFiGeneric.cpp:1035] _eventCallback(): Arduino Event: 14 - AP_STAIPASSIGNED
V: WAP request 302: host ���?, url ���?
V: WAP request 302: host T��?, url ���?
V: WorkManager: status changed 0 0
V: CommandScheduler: service failed to get time
V: WorkManager: status changed 0 0
V: CommandScheduler: service failed to get time
V: WorkManager: status changed 0 0
V: WAP request 302: host 
��?, url <��?
V: WAP request 302: host ���?, url 
��?
V: WorkManager: status changed 0 0
V: CommandScheduler: service failed to get time
V: WorkManager: status changed 0 0
V: CommandScheduler: service failed to get time
E (67171) task_wdt: Task watchdog got triggered. The following tasks did not reset the watchdog in time:
E (67171) task_wdt:  - async_tcp (CPU 0)
E (67171) task_wdt: Tasks currently running:
E (67171) task_wdt: CPU 0: IDLE
E (67171) task_wdt: CPU 1: loopTask
E (67171) task_wdt: Aborting.

abort() was called at PC 0x400f9cb0 on core 0

Backtrace: 0x400843b5:0x3ffbed1c |<-CORRUPTED

  #0  0x400843b5:0x3ffbed1c in panic_abort at /Users/ficeto/Desktop/ESP32/ESP32S2/esp-idf-public/components/esp_system/panic.c:408

ELF file SHA256: 4529b15ccf67df0c

E (6960) esp_core_dump_flash: Core dump flash config is corrupted! CRC=0x7bd5c66f instead of 0x0
Rebooting...
ets Jun  8 2016 00:22:57

rst:0xc (SW_CPU_RESET),boot:0x13 (SPI_FAST_FLASH_BOOT)
configsip: 0, SPIWP:0xee
clk_drv:0x00,q_drv:0x00,d_drv:0x00,cs0_drv:0x00,hd_drv:0x00,wp_drv:0x00
mode:DIO, clock div:2
load:0x3fff0030,len:1184
load:0x40078000,len:13192
load:0x40080400,len:3028
entry 0x400805e4
E (573) esp_core_dump_flash: No core du��partition found!
E (573) esp_core_dump_flash: No core dump partition found!
[     8][D][esp32-hal-cpu.c:244] setCpuFrequencyMhz(): PLL: 480 / 2 = 240 Mhz, APB: 80000000 Hz
I: Tranquil 4.5.2 (built Jul 25 2023 15:38:13)
[    43][E][Preferences.cpp:50] begin(): nvs_open failed: NOT_FOUND
[    43][E][Preferences.cpp:50] begin(): nvs_open failed: NOT_FOUND
[    45][D][FileManager.cpp:33] setup(): [FileManager] setup with config: {"spiffsEnabled":1,"spiffsFormatIfCorrupt":1,"sdEnabled":1,"sdLanes":1}
[   144][I][FileManager.cpp:57] setup(): [FileManager] SPIFFS registered, total size: 1013036, used: 805961
[   144][I][FileManager.cpp:70] setup(): [FileManager] setup SD mode SDMMC
E (372) sdmmc_common: sdmmc_init_ocr: send_op_cond (1) returned 0x107
E (373) vfs_fat_sdmmc: sdmmc_card_init failed (0x107).
[   379][E][FileManager.cpp:150] setup(): [FileManager] !!!!!!!!!!!!!!!!!!!!!!!!!!!
[   386][E][FileManager.cpp:151] setup(): [FileManager] failed to init SD, error ESP_ERR_TIMEOUT
[   395][E][FileManager.cpp:152] setup(): [FileManager] !!!!!!!!!!!!!!!!!!!!!!!!!!!
[   402][E][FileManager.cpp:177] setup(): [FileManager] filesystems must both be marked online to ensure functionality...
[   413][E][FileManager.cpp:178] setup(): [FileManager] SD: offline
[   419][E][FileManager.cpp:179] setup(): [FileManager] SPIFFS: online
[   426][D][esp32FOTA.cpp:141] setString(): Assigned value: Tranquil <= Tranquil
[   432][D][esp32FOTA.cpp:141] setString(): Assigned value: https://otaserver.vigue.me/Tranquil/manifest <= https://otaserver.vigue.me/Tranquil/manifest
[   446][E][Preferences.cpp:50] begin(): nvs_open failed: NOT_FOUND
[   452][E][Preferences.cpp:50] begin(): nvs_open failed: NOT_FOUND
[   458][E][Preferences.cpp:50] begin(): nvs_open failed: NOT_FOUND
[   464][E][Preferences.cpp:50] begin(): nvs_open failed: NOT_FOUND
[   490][D][WiFiGeneric.cpp:1035] _eventCallback(): Arduino Event: 0 - WIFI_READY
[   590][V][WiFiGeneric.cpp:340] _arduino_event_cb(): STA Started
[   591][D][WiFiGeneric.cpp:1035] _eventCallback(): Arduino Event: 2 - STA_START
I: CommandScheduler: config {}
I: LedStrip: LEDs (RGBW 1) TSL enabled: 1 TSL SDA: 16 TSL SCL: 17 count 143
[   626][I][esp32-hal-i2c.c:75] i2cInit(): Initialising I2C Master: sda=16 scl=17 freq=100000
[   629][W][Wire.cpp:301] begin(): Bus already started in Master Mode.
I: LedStrip: TSL2561 detected!
I: Constructing SandBotRotary
I: MotionHelper: configMotionPipeline len 100, blockDistMM 1.00 (0=no-max), allowOoB N, jnDev 0.05
I: Axis0 params maxSpeed 15.00, acceleration 25.00, stepsPerRot 38400.00, unitsPerRot 1.00, maxRPM 4.00
I: Axis0 params minVal 0.00 (0), maxVal 0.00 (0), isDominant 0, homeOffVal 0.00, homeOffSteps 0
I: RampGenIO: Axis0 (step pin 19, dirn pin 21)
I: Axis0EndStop0 (sense 22, level 0, type 1)
I: Axis1 params maxSpeed 15.00, acceleration 25.00, stepsPerRot 3200.00, unitsPerRot 40.50, maxRPM 30.00
I: Axis1 params minVal 0.00 (0), maxVal 145.00 (1), isDominant 0, homeOffVal 0.00, homeOffSteps 0
I: RampGenIO: Axis1 (step pin 27, dirn pin 3)
I: Axis1EndStop0 (sense 23, level 0, type 1)
I: MotionHoming: config sequence FR3;A+38400n;B+3200;#;A+38400N;B+3200;#;A+200;#B+400;#;B+30000n;#;B-30000N;#;B-340;#;A=h;B=h;$
V: TrinamicsController: configure {"model":"SandBotRotary","motionController":{"chip":"TMC2209","TX1":32,"TX2":33,"driver_TOFF":4,"run_current":600,"microsteps":16,"stealthChop":1},"homing":{"homingSeq":"FR3;A+38400n;B+3200;#;A+38400N;B+3200;#;A+200;#B+400;#;B+30000n;#;B-30000N;#;B-340;#;A=h;B=h;$","maxHomingSecs":120},"blockDistanceMM":1,"allowOutOfBounds":0,"stepEnablePin":"25","stepEnLev":0,"stepDisableSecs":30,"axis0":{"maxSpeed":15,"maxAcc":25,"maxRPM":4,"stepsPerRot":38400,"stepPin":"19","dirnPin":"21","dirnRev":"1","endStop0":{"sensePin":"22","actLvl":0,"inputType":"INPUT"}},"axis1":{"maxSpeed":15,"maxAcc":25,"maxRPM":30,"stepsPerRot":3200,"unitsPerRot":40.5,"maxVal":145,"stepPin":"27","dirnRev":"1","dirnPin":"3","endStop0":{"sensePin":"23","actLvl":0,"inputType":"INPUT"}}}
I: MotorEnabler: (pin 25, actLvl 0, disableAfter 30.00s)
I: RampGenerator: Starting ISR timer for direct stepping
[   912][W][esp32-hal-timer.c:226] timerAttachInterruptFlag(): EDGE timer interrupt is not supported! Setting to LEVEL...
I: WorkManager: cmdsAtStart <>
I: WorkManager: startup commands <>
V: WorkManager: status changed 0 0
I: WiFiManager: notConn WiFi.begin SSID  attempt 0
I: WiFiManager: starting softap (Tranquil)
[  2025][V][WiFiGeneric.cpp:343] _arduino_event_cb(): STA Stopped
[  2028][V][WiFiGeneric.cpp:392] _arduino_event_cb(): AP Started
[  2028][D][WiFiGeneric.cpp:1035] _eventCallback(): Arduino Event: 3 - STA_STOP
[  2035][D][WiFiGeneric.cpp:1035] _eventCallback(): Arduino Event: 10 - AP_START
[  2038][V][WiFiGeneric.cpp:395] _arduino_event_cb(): AP Stopped
[  2042][V][WiFiGeneric.cpp:97] set_esp_interface_ip(): Configuring SoftAP static IP: 8.8.4.4, MASK: 255.255.255.0, GW: 8.8.4.4
[  2048][V][WiFiGeneric.cpp:392] _arduino_event_cb(): AP Started
[  2048][D][WiFiGeneric.cpp:1035] _eventCallback(): Arduino Event: 11 - AP_STOP
[  2072][D][WiFiGeneric.cpp:1035] _eventCallback(): Arduino Event: 10 - AP_START
[  2081][V][WiFiGeneric.cpp:143] set_esp_interface_ip(): SoftAP: 8.8.4.4 | Gateway: 8.8.4.4 | DHCP Start: 0.0.0.0 | Netmask: 255.255.255.0
[  2091][V][WiFiGeneric.cpp:190] set_esp_interface_ip(): DHCP Server Range: 8.8.4.5 to 8.8.4.15
I: WiFiManager:  softap ip: 8.8.4.4
I: WebServer: begun
[  6840][V][WiFiGeneric.cpp:407] _arduino_event_cb(): AP Station Connected: MAC: 3c:21:9c:82:e8:3f, AID: 1
[  6842][D][WiFiGeneric.cpp:1035] _eventCallback(): Arduino Event: 12 - AP_STACONNECTED
[  6963][V][WiFiGeneric.cpp:421] _arduino_event_cb(): AP Station IP Assigned:8.8.4.5
[  6965][D][WiFiGeneric.cpp:1035] _eventCallback(): Arduino Event: 14 - AP_STAIPASSIGNED
V: WAP request 302: host P��?, url ���?
V: WAP request 302: host ���?, url ��?
V: WAP request 302: host �=�?, url �=�?
V: WAP request 302: host \��?, url ���?
V: WorkManager: status changed 0 0
V: CommandScheduler: service failed to get time
V: WorkManager: status changed 0 0
[ 21884][V][WiFiGeneric.cpp:414] _arduino_event_cb(): AP Station Disconnected: MAC: 3c:21:9c:82:e8:3f, AID: 1
[ 21885][D][WiFiGeneric.cpp:1035] _eventCallback(): Arduino Event: 13 - AP_STADISCONNECTED
V: CommandScheduler: service failed to get time

**Comment by ScottFal** [comment]
are you clearing the flash before uploading, are you building(yarn && yarn build) TranquilVue and moving the files from "dist" into the "data" folder, are you uploading file system image in the platformIO left pannel

**Comment by acvigue** [comment]
console logs?

**Comment by hackintoshlover** [comment]
> are you clearing the flash before uploading, are you building(yarn && yarn build) TranquilVue and moving the files from "dist" into the "data" folder, are you uploading file system image in the platformIO left pannel

Yes to all

**Comment by hackintoshlover** [comment]
> console logs?

ets Jun  8 2016 00:22:57

rst:0x1 (POWERON_RESET),boot:0x13 (SPI_FAST_FLASH_BOOT)
configsip: 0, SPIWP:0xee
clk_drv:0x00,q_drv:0x00,d_drv:0x00,cs0_drv:0x00,hd_drv:0x00,wp_drv:0x00
mode:DIO, clock div:2
load:0x3fff0030,len:1184
load:0x40078000,len:13192
load:0x40080400,len:3028
entry 0x400805e4
E (562) esp_core_dump_flash: No core d⸮f^⸮partition found!
E (562) esp_core_dump_flash: No core dump partition found!
I: Tranquil 4.5.2 (built Jul 25 2023 16:22:03)
[    41][E][Preferences.cpp:50] begin(): nvs_open failed: NOT_FOUND
E (353) sdmmc_common: sdmmc_init_ocr: send_op_cond (1) returned 0x107
E (354) vfs_fat_sdmmc: sdmmc_card_init failed (0x107).
[   360][E][FileManager.cpp:150] setup(): [FileManager] !!!!!!!!!!!!!!!!!!!!!!!!!!!
[   367][E][FileManager.cpp:151] setup(): [FileManager] failed to init SD, error ESP_ERR_TIMEOUT
[   376][E][FileManager.cpp:152] setup(): [FileManager] !!!!!!!!!!!!!!!!!!!!!!!!!!!
[   383][E][FileManager.cpp:177] setup(): [FileManager] filesystems must both be marked online to ensure functionality...
[   394][E][FileManager.cpp:178] setup(): [FileManager] SD: offline
[   400][E][FileManager.cpp:179] setup(): [FileManager] SPIFFS: online
[   407][E][Preferences.cpp:50] begin(): nvs_open failed: NOT_FOUND
[   412][E][Preferences.cpp:50] begin(): nvs_open failed: NOT_FOUND
[   418][E][Preferences.cpp:50] begin(): nvs_open failed: NOT_FOUND
[   424][E][Preferences.cpp:50] begin(): nvs_open failed: NOT_FOUND
I: CommandScheduler: config {}
I: LedStrip: LEDs (RGBW 1) TSL enabled: 1 TSL SDA: 16 TSL SCL: 17 count 143
I: LedStrip: TSL2561 detected!
I: Constructing SandBotRotary
I: MotionHelper: configMotionPipeline len 100, blockDistMM 1.00 (0=no-max), allowOoB N, jnDev 0.05
I: Axis0 params maxSpeed 15.00, acceleration 25.00, stepsPerRot 38400.00, unitsPerRot 1.00, maxRPM 4.00
I: Axis0 params minVal 0.00 (0), maxVal 0.00 (0), isDominant 0, homeOffVal 0.00, homeOffSteps 0
I: RampGenIO: Axis0 (step pin 19, dirn pin 21)
I: Axis0EndStop0 (sense 22, level 0, type 1)
I: Axis1 params maxSpeed 15.00, acceleration 25.00, stepsPerRot 3200.00, unitsPerRot 40.50, maxRPM 30.00
I: Axis1 params minVal 0.00 (0), maxVal 145.00 (1), isDominant 0, homeOffVal 0.00, homeOffSteps 0
I: RampGenIO: Axis1 (step pin 27, dirn pin 3)
I: Axis1EndStop0 (sense 23, level 0, type 1)
I: MotionHoming: config sequence FR3;A+38400n;B+3200;#;A+38400N;B+3200;#;A+200;#B+400;#;B+30000n;#;B-30000N;#;B-340;#;A=h;B=h;$
I: MotorEnabler: (pin 25, actLvl 0, disableAfter 30.00s)
I: RampGenerator: Starting ISR timer for direct stepping
I: WorkManager: cmdsAtStart <>
I: WorkManager: startup commands <>
I: WiFiManager: notConn WiFi.begin SSID Home attempt 0
I: WiFiManager: starting softap (Tranquil)
I: WiFiManager:  softap ip: 8.8.4.4
I: WebServer: begun
I: WiFiManager: notConn WiFi.begin SSID Home attempt 1

**Comment by hackintoshlover** [comment]
Below is the log snippet upon connecting to AP:

I: WiFiManager: notConn WiFi.begin SSID Home attempt 2
E (150435) task_wdt: Task watchdog got triggered. The following tasks did not reset the watchdog in time:
E (150435) task_wdt:  - async_tcp (CPU 0)
E (150435) task_wdt: Tasks currently running:
E (150435) task_wdt: CPU 0: IDLE
E (150435) task_wdt: CPU 1: loopTask
E (150435) task_wdt: Aborting.

abort() was called at PC 0x400f9028 on core 0


Backtrace: 0x400843b5:0x3ffbed1c |<-CORRUPTED

**Comment by hackintoshlover** [comment]
Hi Aiden,
So magically everything now works. The webpage loads but with error saying manifest file not found.
![Screenshot (148)](https://github.com/acvigue/TranquilFirmware/assets/40655406/c231bcfe-4968-44eb-88b7-ffc17cc2c5b1)
Below is the main screen upon loading:
![Screenshot (149)](https://github.com/acvigue/TranquilFirmware/assets/40655406/e383196f-3244-4315-9653-8c4aca7a62ee)
Next whenever i click on Playlists or Patterns icon, it asks to login. Where to find credentials.
![Screenshot (153)](https://github.com/acvigue/TranquilFirmware/assets/40655406/74b62bf4-99a2-4341-be3d-ee44bb715d16)
![Screenshot (154)](https://github.com/acvigue/TranquilFirmware/assets/40655406/1741c7f5-4fbf-405e-a323-a296a92fc937)
![Screenshot (149)](https://github.com/acvigue/TranquilFirmware/assets/40655406/0c87b2bf-46ea-42a0-8721-06d2d7264420)

I guess till the manifest file is not found and patterns does not open, we will not be able to use the beautiful app.
Also how to configure different robots and pin assignments using webpage? 
Kindly help with this.

**Comment by acvigue** [comment]
Again, the sd card is required for everything to function. I cannot help you until you have a working SD card. The pin assignments/robotconfig are configured using the API as described in the README.

**Comment by hackintoshlover** [comment]
Ok I'll try to get the sd card to work.
But what the manifest file not found error? Is that normal?
Also how do i login?

**Comment by acvigue** [comment]
But what the manifest file not found error? Is that normal?

SD CARD.

Also how do i login?

TranquilAPI.
