### ISSUE TITLE
HTTP-404 resp manifest.json Tranquil-UI

### ISSUE THREAD

**Issue by 4bits1010** [acvigue/RBotFirmware#8]
I'm receiving a 404 on the manifest.json file from the UI for a GET /files/sd/manifest.json

I have confirmed the file does now exist on my SDCard '{"patterns":[],"playlists":[]}'

This is a fresh compile with the latest repo version and an erased ESP32.  The file didnt exist on my SDcard previously, after boot the file was detected missing by FileManager.cpp and it created the above file. 

Running latest
I: Tranquil 4.5.2 (built Jul 25 2023 12:59:41)

Console output:
[    45][D][FileManager.cpp:33] setup(): [FileManager] setup with config: {"spiffsEnabled":1,"spiffsFormatIfCorrupt":1,"sdEnabled":1,"sdSPI":1,"sdMISO":"21","sdMOSI":"19","sdCLK":"5","sdCS":"33"}
[   146][I][FileManager.cpp:57] setup(): [FileManager] SPIFFS registered, total size: 1013036, used: 805961
[   147][I][FileManager.cpp:70] setup(): [FileManager] setup SD mode SDSPI
[   151][I][FileManager.cpp:87] setup(): [FileManager] setup SDSPI pins MOSI:19 MISO:21 CLK:5 CS:33
[   221][I][FileManager.cpp:156] setup(): [FileManager] SD registered
[   229][I][FileManager.cpp:171] setup(): [FileManager] pattern manifest found

@acvigue thank you again for the project, I really like the tweaks you have added.

**Comment by acvigue** [comment]
Is that the entire verbose (& coredebuglevel 5) console log? I'm having trouble reproducing this.

**Comment by 4bits1010** [comment]
full output below:

[     6][D][esp32-hal-cpu.c:244] setCpuFrequencyMhz(): PLL: 480 / 2 = 240 Mhz, APB: 80000000 Hz
**I: Tranquil 4.5.2 (built Jul 25 2023 12:59:41)**
[    44][E][Preferences.cpp:50] begin(): nvs_open failed: NOT_FOUND
[    45][D][FileManager.cpp:33] setup(): [FileManager] setup with config: {"spiffsEnabled":1,"spiffsFormatIfCorrupt":1,"sdEnabled":1,"sdSPI":1,"sdMISO":"21","sdMOSI":"19","sdCLK":"5","sdCS":"33"}
[   146][I][FileManager.cpp:57] setup(): [FileManager] SPIFFS registered, total size: 1013036, used: 805961
[   147][I][FileManager.cpp:70] setup(): [FileManager] setup SD mode SDSPI
[   152][I][FileManager.cpp:87] setup(): [FileManager] setup SDSPI pins MOSI:19 MISO:21 CLK:5 CS:33
**[   221][I][FileManager.cpp:156] setup(): [FileManager] SD registered
[   229][I][FileManager.cpp:171] setup(): [FileManager] pattern manifest found**
[   230][D][esp32FOTA.cpp:141] setString(): Assigned value: Tranquil <= Tranquil
[   232][D][esp32FOTA.cpp:141] setString(): Assigned value: https://otaserver.vigue.me/Tranquil/manifest <= https://otaserver.vigue.me/Tranquil/manifest
[   246][E][Preferences.cpp:50] begin(): nvs_open failed: NOT_FOUND
[   252][E][Preferences.cpp:50] begin(): nvs_open failed: NOT_FOUND
[   258][E][Preferences.cpp:50] begin(): nvs_open failed: NOT_FOUND
[   264][E][Preferences.cpp:50] begin(): nvs_open failed: NOT_FOUND
[   289][D][WiFiGeneric.cpp:1035] _eventCallback(): Arduino Event: 0 - WIFI_READY
[   384][V][WiFiGeneric.cpp:340] _arduino_event_cb(): STA Started
[   385][D][WiFiGeneric.cpp:1035] _eventCallback(): Arduino Event: 2 - STA_START
I: CommandScheduler: config {}
I: LedStrip: LEDs (RGBW 0) TSL enabled: 0 TSL SDA: 0 TSL SCL: 0 count 2
I: Constructing SandBotRotary
I: MotionHelper: configMotionPipeline len 100, blockDistMM 1.00 (0=no-max), allowOoB N, jnDev 0.05
I: Axis0 params maxSpeed 100.00, acceleration 100.00, stepsPerRot 1.00, unitsPerRot 1.00, maxRPM 300.00
I: Axis0 params minVal 0.00 (0), maxVal 0.00 (0), isDominant 0, homeOffVal 0.00, homeOffSteps 0
I: RampGenIO: Axis0 (step pin 14, dirn pin 32)
I: Axis0EndStop0 (sense 36, level 0, type 1)
I: Axis1 params maxSpeed 100.00, acceleration 100.00, stepsPerRot 1.00, unitsPerRot 1.00, maxRPM 300.00
I: Axis1 params minVal 0.00 (0), maxVal 0.00 (0), isDominant 0, homeOffVal 0.00, homeOffSteps 0
I: RampGenIO: Axis1 (step pin 27, dirn pin 15)
I: Axis1EndStop0 (sense 39, level 0, type 1)
I: MotionHoming: config sequence FR3;A+38400n;B+3200;#;A+38400N;B+3200;#;A+200;#B+400;#;B+30000n;#;B-30000N;#;B-340;#;A=h;B=h;$
V: TrinamicsController: configure {"model":"SandBotRotary","homing":{"homingSeq":"FR3;A+38400n;B+3200;#;A+38400N;B+3200;#;A+200;#B+400;#;B+30000n;#;B-30000N;#;B-340;#;A=h;B=h;$","maxHomingSecs":120},"blockDistanceMM":1,"allowOutOfBounds":0,"stepEnablePin":"12","stepEnLev":0,"stepDisableSecs":30,"axis0":{"stepPin":"14","dirnPin":"32","endStop0":{"sensePin":"36","actLvl":0,"inputType":"INPUT"}},"axis1":{"stepPin":"27","dirnPin":"15","endStop0":{"sensePin":"39","actLvl":0,"inputType":"INPUT"}}}
I: MotorEnabler: (pin 12, actLvl 0, disableAfter 30.00s)
I: RampGenerator: Starting ISR timer for direct stepping
[   551][W][esp32-hal-timer.c:226] timerAttachInterruptFlag(): EDGE timer interrupt is not supported! Setting to LEVEL...
I: WorkManager: cmdsAtStart <>
I: WorkManager: startup commands <>
V: WorkManager: status changed 0 0
I: WiFiManager: notConn WiFi.begin SSID iot attempt 0
[  2024][V][WiFiGeneric.cpp:97] set_esp_interface_ip(): Configuring Station static IP: 0.0.0.0, MASK: 0.0.0.0, GW: 0.0.0.0
[  2701][V][WiFiGeneric.cpp:355] _arduino_event_cb(): STA Connected: SSID: iot, BSSID: d4:5d:64:f6:d6:29, Channel: 7, Auth: WPA_WPA2_PSK
[  2702][D][WiFiGeneric.cpp:1035] _eventCallback(): Arduino Event: 4 - STA_CONNECTED
[  2713][V][WiFiGeneric.cpp:369] _arduino_event_cb(): STA Got New IP:172.16.8.235
[  2717][D][WiFiGeneric.cpp:1035] _eventCallback(): Arduino Event: 7 - STA_GOT_IP
[  2724][D][WiFiGeneric.cpp:1098] _eventCallback(): STA IP: 172.16.8.235, MASK: 255.255.255.0, GW: 172.16.8.1
**I: WiFiManager: GotIP 172.16.8.235
I: WebServer: begun**
I: WiFiManager: mDNS responder started with hostname Tranquil
V: WorkManager: status changed 0 0
I: NTPClient: service - configTime set
V: WorkManager: status changed 0 0
V: WebServer: Calling settings/led url /settings/led
V: RestAPIRobot: GetLEDConfig { "rslt": "unknown" }
**E (29271) diskio_sdmmc: Check status failed (0x107)
E (29272) diskio_sdmmc: Check status failed (0x107)
E (29272) diskio_sdmmc: Check status failed (0x107)
E (29275) diskio_sdmmc: Check status failed (0x107)
E (29279) diskio_sdmmc: Check status failed (0x107)
V: request 404: host 172.16.8.235, url ���?␟**
I: RestAPIRobot: SetLedBody len 227, {"ledOn":0,"ledBrightness":59,"primaryRedVal":127,"primaryGreenVal":127,"primaryBlueVal":127,"secRedVal":127,"secGreenVal":127,"secBlueVal":127,"effectID":0,"effectSpeed":50,"autoDim":0,"autoDimStrength":10,"ledAngleOffset":10}
V: WebServer: Calling settings/led url /settings/led
I: RestAPIRobot: SetLed /settings/led
V: WorkManager: status changed 0 0

**Comment by acvigue** [comment]
Seeing as how the FileManager is able to determine that the manifest file exists, and that the web server only uses standard `fopen/fread/fwrite` APIs, I have no suggestions, but I would believe something is causing noise on the SPI lines (improper pullup resistors?)

Reformat as FAT32 and try again?

- aiden

**Comment by 4bits1010** [comment]
felt a bit odd to me as well, i added the below code to get some details back about the card.  I also reinserted the card and **poof it is now working** and i can load your sweet UI and run some GET req to various files on my card. Thank you for your time and support, must have been a bad contact so your instincts were on point

`sdmmc_card_print_info(stdout,pCard);`

SD console output:
> Name: SD   
> Type: SDHC/SDXC
> Speed: 20 MHz
> Size: 7887MB
